default_stages: [ pre-commit, prepare-commit-msg ]

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.3.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        exclude: docs/specs/.*\.pdf
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
        stages: [ pre-merge-commit ]

  - repo: local
    hooks:
      - id: clang-format
        name: Run clang-format on changed lines
        language: script
        entry: scripts/git-hooks/pre-commit-clang-format
        types: [c, c++]
