libc_a_SOURCES += %D%/syscalls.c

libc_a_SOURCES += %D%/isatty.c
libc_a_SOURCES += %D%/killpg.c

libc_a_SOURCES += %D%/dirfd.c
libc_a_SOURCES += %D%/opendir.c
libc_a_SOURCES += %D%/readdir.c
libc_a_SOURCES += %D%/seekdir.c
libc_a_SOURCES += %D%/closedir.c
