PORT_NAME       := dash
PORT_TYPE       := automake
PORT_VERSION    := 0.5.13
PORT_URL        := http://gondor.apana.org.au/~herbert/dash/files/dash-$(PORT_VERSION).tar.gz

INSTALL_DIR := $(INSTALL_DIR)/usr

include ../port.mk
