name: Build

on:
  pull_request:
  push:
    branches:
    - master

jobs:

  build-kernel:
    name: Kernel
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

      # We use nix flakes to setup environment
    - name: Install Nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Build Kernel
      run: |
        nix build .#kernel -L
