name: Testing

on:
  pull_request:
  push:
    branches:
    - master

jobs:

  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

      # We use nix flakes to setup environment
    - name: Install Nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Test
      run: |
        nix develop .#test --command make check
